SET foreign_key_checks = 0;
DROP TABLE IF EXISTS coupon_code_reservation;
DROP TABLE IF EXISTS coupon_engine_config_audit;
DROP TABLE IF EXISTS coupon_engine_config;
DROP TABLE IF EXISTS coupon_disc_req_prod_audit;
DROP TABLE IF EXISTS coupon_disc_req_code_audit;
DROP TABLE IF EXISTS coupon_discount_summary;
DROP TABLE IF EXISTS coupon_discount_req_prod;
DROP TABLE IF EXISTS coupon_discount_req_code;
DROP TABLE IF EXISTS coupon_discount_product;
DROP TABLE IF EXISTS coupon_discount_code;
DROP TABLE IF EXISTS coupon_discount;
DROP TABLE IF EXISTS coupon_discounting_rule;
DROP TABLE IF EXISTS coupon_discount_req;
DROP TABLE IF EXISTS coupon_disc_req_audit;
-- DR-OP TABLE IF EXISTS auth_users;
-- DR-OP TABLE IF EXISTS auth_roles;
-- DR-OP TABLE IF EXISTS auth_user_role_mapping;
DROP TABLE IF EXISTS coupon_code;
DROP TABLE IF EXISTS coupon;
DROP TABLE IF EXISTS coupon_product_adapter;
-- DR-OP TABLE IF EXISTS packages;
-- DR-OP TABLE IF EXISTS services;
DROP TABLE IF EXISTS coupon_usage_summary;
DROP TABLE IF EXISTS coupon_product_adapter_mapping;
DROP TABLE IF EXISTS coupon_brand_mapping;
DROP TABLE IF EXISTS coupon_area_mapping;
DROP TABLE IF EXISTS coupon_referrer_mapping;
-- DR-OP TABLE IF EXISTS brands;
-- DR-OP TABLE IF EXISTS areas;
-- DR-OP TABLE IF EXISTS referrers;
DROP TABLE IF EXISTS coupon_audit;
DROP TABLE IF EXISTS coupon_core_audit;
DROP TABLE IF EXISTS coupon_brand_mapping_audit;
DROP TABLE IF EXISTS coupon_product_adapter_mapping_audit;
DROP TABLE IF EXISTS coupon_discounting_rule_audit;
DROP TABLE IF EXISTS coupon_area_mapping_audit;
DROP TABLE IF EXISTS coupon_referrer_mapping_audit;
DROP TABLE IF EXISTS coupon_engine_comm_audit;
SET foreign_key_checks = 1;