SET foreign_key_checks = 0;
DROP TABLE coupon_category_map;
DROP TABLE coupon_code_reservation;
DROP TABLE coupon_product_map;
DROP TABLE coupon_event_type;
DROP TABLE coupon_engine_config_audit;
DROP TABLE coupon_engine_config;
DROP TABLE coupon_disc_req_prod_audit;
DROP TABLE coupon_disc_req_code_audit;
DROP TABLE coupon_discount_summary;
DROP TABLE coupon_discount_req_prod;
DROP TABLE coupon_discount_req_code;
DROP TABLE coupon_discount_product;
DROP TABLE coupon_discount_code;
DROP TABLE coupon_discounting_rule_interval;
DROP TABLE coupon_discount;
DROP TABLE coupon_discounting_rule;
DROP TABLE coupon_discount_req;
DROP TABLE coupon_disc_req_audit;
DROP TABLE test_user;
DROP TABLE test_product;
DROP TABLE test_category;
DROP TABLE coupon_code;
DROP TABLE coupon;
SET foreign_key_checks = 1;