SET foreign_key_checks = 0;
TRUNCATE TABLE coupon_category_map;
TRUNCATE TABLE coupon_code_reservation;
TRUNCATE TABLE coupon_product_map;
TRUNCATE TABLE coupon_event_type;
TRUNCATE TABLE coupon_engine_config_audit;
TRUNCATE TABLE coupon_engine_config;
TRUNCATE TABLE coupon_disc_req_prod_audit;
TRUNCATE TABLE coupon_disc_req_code_audit;
TRUNCATE TABLE coupon_discount_summary;
TRUNCATE TABLE coupon_discount_req_prod;
TRUNCATE TABLE coupon_discount_req_code;
TRUNCATE TABLE coupon_discount_product;
TRUNCATE TABLE coupon_discount_code;
TRUNCATE TABLE coupon_discounting_rule_interval;
TRUNCATE TABLE coupon_discount;
TRUNCATE TABLE coupon_discounting_rule;
TRUNCATE TABLE coupon_discount_req;
TRUNCATE TABLE coupon_disc_req_audit;
TRUNCATE TABLE test_user;
TRUNCATE TABLE test_product;
TRUNCATE TABLE test_category;
TRUNCATE TABLE coupon_code;
TRUNCATE TABLE coupon;
SET foreign_key_checks = 1;